name: BrickFreedomMod
main: me.StevenLawson.TotalFreedomMod.TotalFreedomMod
version: 4.3
description: Plugin for the Brick Freedom server, TotalFreedom's Associated Server.
softdepend: [BukkitTelnet, WorldEdit, Essentials]
authors: [Madgeek1450, DarthSalamon]

# plugin.yml is no longer used to define commands.
